namespace go online_interview
with_client=false

struct QuestionAssessReq
{
    i64 id (remark="id"),
    i64 attitude (remark="我的态度：1：满意  2：不满意"),
}

struct Question
{
    i64 id (remark="id"),
    i64 questionId (remark="问题id"),
    string content (remark="内容"),
    i64 attitude (remark="我的态度：1：满意  2：不满意"),
    string notes(remark="备注"),
}

struct Tag
{
    i64 tagId (remark="标签id"),
    string content (remark="内容"),
    i64 attitude (remark="我的态度：1：符合  2：不符合"),
}

struct EditTagReq
{
    i64 tagId (remark="标签id"),
    i64 attitude (remark="我的态度：1：符合  2：不符合"),
}

struct InterviewEvaluate
{
    i64 InterviewId (remark="面试id"),
    string content (remark="内容"),
    i64 attitude (remark="3: 待定，4: 通过， 5:不通过"),
}

struct InterviewRecordVO
{
    i64 id (remark="面试记录id"),
    i32 type (remark="记录类型 1:笔记, 2:标记, 3:提问"),
    i64 attitude (remark="我的态度：1：满意  2：不满意"),
    string remark (binding="required", remark="备注信息"),
    string content (binding="required", remark="笔记|标记|提问的内容"),
    string ext (remark="拓展信息"),
}

struct InterviewAllInfo
{
    string playbackUrl(remark="回放地址"),
    string resume (remark="简历地址"),
    string dialogue (remark="对话内容"),
    list<struct InterviewRecordVO> recordList(remark="面试记录列表"),
    list<struct Tag> tag(remark="候选人标签"),
    struct InterviewEvaluate interviewEvaluate(remark="面试最终评价"),
}


struct InterviewId
{
    i64 interviewId (remark="面试id"),
}

struct TagContent
{
    i64 interviewId (remark="面试id"),
    string content (remark="标签内容"),
}

struct StepInfo
{
    i64 interviewId (remark="面试id"),
    i64 step (remark="流程状态：0:欢迎页, 1:简历分析, 2:面试题准备, 3:画面测试"),
}

service EndInterview URL="/api/v1/online-interview"
{
    # 问题评价
    ("对问题的进行评价和备注@prod=12")
    POST URL="question/mark" void questionAssess(struct QuestionAssessReq req),
    ("获取所有问题列表@prod=12")
    GET URL="question/get-all" list<struct Question> getQuestions(i64 interviewId),


    # 标签
    ("AI打标签@prod=12")
    POST URL="tag/gene" void geneAITag(struct InterviewId interviewId),
    ("获取所有能力标签(ai+人工)@prod=12")
    POST URL="tag/get-all" list<struct Tag> getAllTag(struct InterviewId interviewId),
    ("添加标签@prod=12")
    POST URL="tag/add" i64 addTag(struct TagContent req),
    ("对标签进行点评@prod=12")
    POST URL="tag/edit" void editTag(struct EditTagReq req),

    # 最终面试评价
    ("生成ai面试评价@prod=12")
    POST URL="gene-ai-evaluation" string geneAIEvaluation(struct InterviewId interviewId),
    ("修改面试评价@prod=12")
    POST URL="manual-evaluation" void  manualEvaluate(struct InterviewEvaluate req),
    ("获取最终评价@prod=12")
    GET URL="final-evaluation" struct InterviewEvaluate getFinalEvaluation(i64 id),


    # 获取全部信息
    ("获取全部信息@prod=12")
    GET URL="all-info" struct InterviewAllInfo getAllInfo(i64 id),


    ("获取用户当前流程状态@prod=12")
    GET URL="step/info" i64 getStepInfo(i64 interviewId),
    ("修改用户当前流程状态@prod=12")
    POST URL="step/update" void updateStepInfo(struct StepInfo req),

}